# vim:ft=yaml.ansible
---
- name: Create custom tool directory
  ansible.builtin.file:
    path: "{{ custom_tool_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ gxpriv_user }}"
    group: "{{ galaxy_user }}"


- name: Get uid for {{ gxpriv_user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ gxpriv_user }}"

- name: Get gid for {{ galaxy_user }}
  ansible.builtin.getent:
    database: group
    key: "{{ galaxy_user }}"

- name: Create a lemaitre container
  community.docker.docker_container:
    name: lemaitre
    state: started
    image: ghcr.io/reproducible-bioinformatics/lemaitre:1.1.0
    user: "{{ getent_passwd[gxpriv_user][1] }}"
    groups: "{{ getent_passwd[gxpriv_user][2] }}"
    env:
      TOOL_DIR: "{{ custom_tool_directory }}"
      TOOL_CONF: "{{ tool_conf }}"
    volumes:
      - "{{ custom_tool_directory }}:{{ custom_tool_directory }}:rw"
      - "{{ tool_conf }}:{{ tool_conf }}:rw"
    ports:
      - 9999:8000
