# vim:ft=yaml.ansible
---
- name: Create custom tool directory
  ansible.builtin.file:
    path: "{{ custom_tool_directory }}"
    state: directory
    mode: '0777'
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user }}"

- name: Change permission to tool_conf
  ansible.builtin.file:
    path: "/srv/galaxy/server/lib/galaxy/config/sample/tool_conf.xml.sample"
    mode: '0774'
    owner: "{{ gxpriv_user }}"
    group: "{{ galaxy_user }}"

- name: Get uid for {{ galaxy_user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ galaxy_user }}"

- name: Get gid for {{ galaxy_user }}
  ansible.builtin.getent:
    database: group
    key: "{{ galaxy_user }}"

- name: Copy agent script
  ansible.builtin.template:
    src: "agent.sh"
    dest: "/srv/lemaitre_agent.sh"
    mode: '0700'

- name: Copy agent service
  ansible.builtin.template:
    src: "lemaitre_agent.service"
    dest: "/etc/systemd/system/lemaitre_agent.service"
    mode: '0700'

- name: Start agent service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: lemaitre_agent
    daemon_reload: true

- name: Create a lemaitre container
  community.docker.docker_container:
    name: lemaitre
    state: started
    image: ghcr.io/reproducible-bioinformatics/lemaitre:1.2.0
    user: "{{ getent_passwd[galaxy_user][1] }}"
    groups: "{{ getent_passwd[galaxy_user][2] }}"
    env:
      TOOL_DIR: "{{ custom_tool_directory }}"
      TOOL_CONF: "{{ tool_conf }}"
      COMMAND_PIPE: "{{ command_named_pipe }}"
    volumes:
      - "{{ custom_tool_directory }}:{{ custom_tool_directory }}:rw"
    mounts:
      - type: bind
        source: "{{ command_named_pipe }}"
        target: "{{ command_named_pipe }}"
      - type: bind
        source: "{{ tool_conf }}"
        target: "{{ tool_conf }}"
    ports:
      - 9999:8000
