# vim:ft=yaml.ansible
---
- name: Default production deployment.
  hosts: all
  pre_tasks:
    - name: Install dependencies.
      ansible.builtin.include_role:
        name: deps
  roles:
    - galaxyproject.galaxy
