# vim: ft=yaml.ansible
---
- name: Install prerequisites for Caddy
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gpg
    state: present
    update_cache: true

- name: Download and add the Caddy GPG key
  ansible.builtin.get_url:
    url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
    dest: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    mode: '0644'

- name: Add Caddy repository to sources list
  ansible.builtin.copy:
    content: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/debian any-version main"
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: '0644'

- name: Install Caddy
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: caddy
    state: present

- name: Configure Caddy
  ansible.builtin.template:
    src: "Caddyfile.j2"
    dest: "/etc/caddy/Caddyfile"
    mode: '0644'
  notify:
    - Restart Caddy
