# vim:ft=yaml.ansible
---
- name: Ensure required dependencies are present.
  ansible.builtin.apt:
    name:
      - python3
      - git
      - python3-virtualenv
      - python3-pip
    state: present
